# Generated by Django 3.2.13 on 2022-06-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chaiman'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chaiman',
            new_name='chairman',
        ),
    ]
