# Generated by Django 3.2.13 on 2022-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_chaiman_chairman'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/Default_Chairman.png', upload_to='media/images'),
        ),
    ]
