# Generated by Django 3.2.3 on 2022-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chairman_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='block_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chairman',
            name='house_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
