# Generated by Django 3.2.3 on 2022-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220702_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='about_me',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
