# Generated by Django 3.2.3 on 2022-07-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_chairman_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=75)),
                ('notice_content', models.TextField(max_length=255)),
                ('img', models.ImageField(upload_to='images/notice/')),
                ('video', models.FileField(upload_to='images/notice/video/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
            ],
        ),
    ]
