# Generated by Django 3.2.3 on 2022-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='img',
            field=models.ImageField(null=True, upload_to='images/notice/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='video',
            field=models.FileField(null=True, upload_to='images/notice/video/'),
        ),
    ]
