# Generated by Django 3.2.3 on 2022-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220705_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('total_member', models.CharField(max_length=50)),
                ('number_of_vehicle', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/Member')),
                ('work_info', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
