# Generated by Django 3.2.3 on 2022-07-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='member',
        ),
    ]
