# Generated by Django 3.2.3 on 2022-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_notice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='images/Member/MD.jpg', null=True, upload_to='images/Member'),
        ),
    ]
