# Generated by Django 3.2.3 on 2022-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
