# Generated by Django 3.2.3 on 2022-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_member_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('Member', 'Member')], max_length=10),
        ),
    ]
