# Generated by Django 3.2.3 on 2022-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Email',
            field=models.EmailField(max_length=10, null=True),
        ),
    ]
