# Generated by Django 3.2.3 on 2022-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.EmailField(max_length=75, null=True),
        ),
    ]
